# Generated by Django 3.1.4 on 2020-12-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_score', models.IntegerField(default=0)),
                ('round_won', models.BooleanField(default=False)),
                ('raw_round_score', models.IntegerField(default=0)),
                ('actual_round_score', models.IntegerField(default=0)),
                ('east', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='last_east',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='spiel', to='game.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='last_winner',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='das_spiel', to='game.player'),
        ),
    ]
