# Generated by Django 3.1.4 on 2020-12-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201220_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_east',
        ),
        migrations.RemoveField(
            model_name='game',
            name='last_winner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='started',
        ),
        migrations.RemoveField(
            model_name='player',
            name='east',
        ),
        migrations.RemoveField(
            model_name='player',
            name='round_won',
        ),
        migrations.AddField(
            model_name='game',
            name='east',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
